=== jrolo92/LMSGI_UD4/Actividad6/Modulos.dtd
<!ELEMENT CFGS_DAW (modulo)+>
<!ELEMENT modulo (nombre_modulo, unidad_didactica+)>
<!ELEMENT nombre_modulo (#PCDATA)>
<!ELEMENT unidad_didactica (numero_unidad, contenidos)>
<!ELEMENT numero_unidad (#PCDATA)>
<!ELEMENT contenidos (tipo, descripción)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripción (#PCDATA)>

=== jrolo92/LMSGI_UD4/Actividad6/Modulos_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CFGS_DAW SYSTEM "Modulos.dtd">
<CFGS_DAW>
    <modulo>
        <nombre_modulo>Programacion</nombre_modulo>
        <unidad_didactica>
            <numero_unidad>2</numero_unidad>
            <contenidos>
                <tipo>JAVA</tipo>
                <descripción>Programacion JAVA usando netbeans</descripción>
            </contenidos>
        </unidad_didactica>
        <unidad_didactica>
            <numero_unidad>3</numero_unidad>
            <contenidos>
                <tipo>Arrays</tipo>
                <descripción>Programacion usando arrays con eclipse</descripción>
            </contenidos>
        </unidad_didactica>
    </modulo>
    <modulo>
        <nombre_modulo>Base de datos</nombre_modulo>
        <unidad_didactica>
            <numero_unidad>3</numero_unidad>
            <contenidos>
                <tipo>Modelo entidad-relacion</tipo>
                <descripción>Aprender a realizar diagramas E-R</descripción>
            </contenidos>
        </unidad_didactica>
        <unidad_didactica>
            <numero_unidad>4</numero_unidad>
            <contenidos>
                <tipo>Modelo relacional</tipo>
                <descripción>Confección de grafos relacionales</descripción>
            </contenidos>
        </unidad_didactica>
    </modulo>
</CFGS_DAW>
