=== jrolo92/LMSGI_UD4/Actividad5/Practica.dtd
<!ELEMENT practicas (alumno*)>
<!ELEMENT alumno (NIF,resultado,obserbaciones?,(ip|mac))>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT mac (#PCDATA)>

=== jrolo92/LMSGI_UD4/Actividad5/Practica_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE practicas SYSTEM "Practica.dtd">
    <practicas>
        <alumno>
            <NIF>98456132T</NIF>
            <resultado>No Apto</resultado>
            <observaciones>Suspenso con un 4,5</observaciones>
            <ip>192.168.23.65</ip>
        </alumno>
        <alumno>
            <NIF>12345678W</NIF>
            <resultado>Apto</resultado>
            <observaciones>Sobresaliente</observaciones>
            <mac>192.168.48.112</mac>
        </alumno>
    </practicas>
